# docker-compose.yml
version: "3"
services:
  web-ui:
    image: dappforce/subsocial-ui:latest
    container_name: bunbi-ui
    restart: on-failure
    network_mode: "host"

  nginx:
    build: ./nginx
    container_name: subsocial-proxy
    image: dappforce/subsocial-proxy:latest
    restart: on-failure
    network_mode: "host"
